version: '3.8'
services:
  backend:
    build: ./Backend
    ports:
      - "3001:3001"
    restart: always
    networks:
      - shoe-network
    depends_on:
      - database

  database:
    image: redis:alpine
    restart: always
    networks:
      - shoe-network

networks:
  shoe-network:
    driver: bridge
