name: CI/CD Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}      # משתמש ב-Secret שהגדרת
          username: ${{ secrets.USERNAME }}  # משתמש ב-Secret שהגדרת
          key: ${{ secrets.SSH_KEY }}    # משתמש ב-Secret שהגדרת
          script: |
            cd /home/ubuntu/nike-project
            git pull origin main
            sudo docker-compose down
            sudo docker-compose up -d --build --force-recreate
            sudo docker system prune -f
            echo "🚀 בוצע ניקוי והרצה מחדש אגרסיבית!"